dbt_northwind:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 20.2.72.244
      user: postgres # replace with real username
      pass: postgres # replace with real password
      port: 5432
      dbname: dbt_demo_db
      schema: dbt
      threads: 4
